import { createPage } from '../../common/weapp-page'
import { concatClassList, px2rpx } from '../../common/style'
import { app } from '../../app/weapps-api'
import { indexModel as handlers } from '../../app/handlers'
// import index from '../../lowcode/indexModel/index'
import lifecyle from '../../lowcode/indexModel/lifecycle'
import state from '../../lowcode/indexModel/state'
import computed from '../../lowcode/indexModel/computed'
import { $page } from './api'
const $app = app;

const widgetProps = { id148: 
   { style: 
      { display: 'flex',
        flexDirection: 'column',
        position: 'relative' },
     classList: [ 'indexModel-content' ],
     title: '',
     _parentId: undefined,
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id141: 
   { style: {},
     classList: [ 'indexModel-banner-content' ],
     title: '',
     _parentId: 'id148',
     _order: 2,
     widgetType: 'gsd-h5-react:Container' },
  id202: 
   { style: { marginBottom: '20rpx' },
     classList: [ 'indexModel-title-banner' ],
     title: '',
     _parentId: 'id141',
     _order: 0,
     widgetType: 'gsd-h5-react:Container' },
  id201: 
   { style: 
      { marginBottom: '13pt',
        display: 'inline',
        color: 'rgb(255, 255, 255)',
        fontSize: '48rpx',
        fontFamily: 'PingFang-SC-Medium' },
     classList: [ 'indexModel-content-topText' ],
     decode: false,
     level: '0',
     maxLines: 1,
     selectable: false,
     space: '',
     text: '数字生态大会',
     textAlign: 'left',
     textColor: 'rgb(255, 255, 255)',
     userSelect: true,
     _parentId: 'id202',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id204: 
   { style: { marginTop: '20rpx' },
     classList: [ 'indexModel-content-info-content' ],
     title: '',
     _parentId: 'id202',
     _order: 3,
     widgetType: 'gsd-h5-react:Container' },
  id203: 
   { style: { width: '40rpx', verticalAlign: 'middle' },
     classList: [],
     color: '',
     name: 'success',
     size: 48,
     src: 'https://main.qcloudimg.com/raw/8d6fdfbf442162a1d30fd7ad3023a8d0.png',
     _parentId: 'id204',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id205: 
   { style: {},
     classList: [ 'indexModel-content-info-text' ],
     decode: false,
     maxLines: 1,
     selectable: false,
     space: '',
     text: '深圳市南山区深南大道10000号',
     userSelect: true,
     _parentId: 'id204',
     _order: undefined,
     widgetType: 'gsd-h5-react:Text' },
  id206: 
   { style: {},
     classList: [ 'indexModel-content-info-content' ],
     title: '',
     _parentId: 'id202',
     _order: 2,
     widgetType: 'gsd-h5-react:Container' },
  id207: 
   { style: {},
     classList: [],
     color: '',
     name: 'success',
     size: 48,
     src: 'https://main.qcloudimg.com/raw/ac893dc3e8c6eb8540028ec89ac604ae.png',
     _parentId: 'id206',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id208: 
   { style: { marginLeft: '20rpx' },
     classList: [ 'indexModel-content-info-text' ],
     decode: false,
     level: '0',
     maxLines: 1,
     selectable: false,
     space: '',
     text: '2021.10.10',
     textAlign: 'left',
     textColor: 'rgb(255, 255, 255)',
     userSelect: true,
     _parentId: 'id206',
     _order: undefined,
     widgetType: 'gsd-h5-react:Text' },
  id228: 
   { style: { height: '414rpx', position: 'static' },
     classList: [],
     title: '',
     _parentId: 'id141',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id143: 
   { style: { width: '100%', height: '600rpx' },
     classList: [ 'indexModel-content-bannerPic' ],
     alt: '[图片]',
     fit: 'cover',
     imgPreview: '',
     lazyLoad: false,
     maskClosable: true,
     mode: 'scaleToFill',
     showMenuByLongpress: false,
     src: 'https://main.qcloudimg.com/raw/a31fa3d509403bd3ede3c860644d1890.png',
     webp: false,
     _parentId: 'id228',
     _order: 0,
     widgetType: 'gsd-h5-react:Image' },
  id149: 
   { style: { display: 'block' },
     classList: [],
     title: '',
     _parentId: 'id148',
     _order: 3,
     widgetType: 'gsd-h5-react:Container' },
  id150: 
   { style: 
      { display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row' },
     classList: [ 'indexModel-index-picture-content' ],
     title: '',
     _parentId: 'id149',
     _order: 0,
     widgetType: 'gsd-h5-react:Container' },
  id151: 
   { style: {},
     classList: [ 'indexModel-index-picture-text' ],
     decode: false,
     level: '0',
     maxLines: 2,
     selectable: false,
     space: '',
     text: '现场照片',
     textAlign: 'left',
     textColor: 'rgb(255, 255, 255)',
     userSelect: true,
     _parentId: 'id150',
     _order: 2,
     widgetType: 'gsd-h5-react:Text' },
  id152: 
   { style: { width: '32rpx', height: '44rpx', position: 'relative' },
     classList: [],
     color: '#ffffff',
     name: 'success',
     size: 42,
     src: 'https://main.qcloudimg.com/raw/ca83370d449050fc5f5d6ba730670c93.png',
     _parentId: 'id150',
     _order: 1,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id153: 
   { style: 
      { marginBottom: '48rpx',
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row' },
     classList: [ 'indexModel-index-entext-content' ],
     title: '',
     _parentId: 'id149',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id154: 
   { style: {},
     classList: [ 'indexModel-index-picture-entext' ],
     decode: false,
     level: '0',
     maxLines: 1,
     selectable: false,
     space: '',
     text: 'Live photos',
     textAlign: 'left',
     textColor: '#878d96',
     userSelect: true,
     _parentId: 'id153',
     _order: 1,
     widgetType: 'gsd-h5-react:Text' },
  id155: 
   { style: { marginRight: '40rpx', marginLeft: '40rpx' },
     classList: [],
     title: '',
     _parentId: 'id149',
     _order: 2,
     widgetType: 'gsd-h5-react:Container' },
  id156: 
   { style: {},
     classList: [ 'indexModel-picture-one' ],
     alt: '[图片]',
     fit: 'cover',
     imgPreview: '',
     lazyLoad: false,
     maskClosable: true,
     mode: 'widthFix',
     showMenuByLongpress: false,
     src: 'https://main.qcloudimg.com/raw/9a8fc91e3b4db7a21e4ef262138feaf1.png',
     webp: false,
     _parentId: 'id155',
     _order: 0,
     widgetType: 'gsd-h5-react:Image' },
  id162: 
   { style: 
      { display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        flexDirection: 'row' },
     classList: [ 'indexModel-picture-two' ],
     title: '',
     _parentId: 'id149',
     _order: 4,
     widgetType: 'gsd-h5-react:Container' },
  id217: 
   { style: { width: '100%', height: '180rpx', marginRight: '10rpx' },
     classList: [],
     title: '',
     _parentId: 'id162',
     _order: 0,
     widgetType: 'gsd-h5-react:Container' },
  id158: 
   { style: { width: '100%', height: '180rpx', position: 'static' },
     classList: [],
     alt: '[图片]',
     fit: 'cover',
     imgPreview: '',
     lazyLoad: false,
     maskClosable: true,
     mode: 'scaleToFill',
     showMenuByLongpress: false,
     src: 'https://main.qcloudimg.com/raw/82b83820a1b902538a990bc75b715fec.png',
     webp: false,
     _parentId: 'id217',
     _order: 0,
     widgetType: 'gsd-h5-react:Image' },
  id218: 
   { style: 
      { width: '100%',
        height: '180rpx',
        marginLeft: '10rpx',
        position: 'relative' },
     classList: [],
     title: '',
     _parentId: 'id162',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id161: 
   { style: { width: '100%', height: '180rpx' },
     classList: [],
     alt: '[图片]',
     fit: 'cover',
     imgPreview: '',
     lazyLoad: false,
     maskClosable: true,
     mode: 'scaleToFill',
     showMenuByLongpress: false,
     src: 'https://main.qcloudimg.com/raw/98605d0355564fe4be47a4737def88db.png',
     webp: false,
     _parentId: 'id218',
     _order: 0,
     widgetType: 'gsd-h5-react:Image' },
  id165: 
   { style: { display: 'flex', flexDirection: 'column' },
     classList: [],
     title: '',
     _parentId: 'id148',
     _order: 4,
     widgetType: 'gsd-h5-react:Container' },
  id166: 
   { style: 
      { display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row' },
     classList: [ 'indexModel-index-picture-content' ],
     title: '',
     _parentId: 'id165',
     _order: 0,
     widgetType: 'gsd-h5-react:Container' },
  id170: 
   { style: {},
     classList: [ 'indexModel-index-picture-text' ],
     decode: false,
     level: '0',
     maxLines: 2,
     selectable: false,
     space: '',
     text: '信息填写',
     textAlign: 'left',
     textColor: 'rgb(255, 255, 255)',
     userSelect: true,
     _parentId: 'id166',
     _order: 2,
     widgetType: 'gsd-h5-react:Text' },
  id171: 
   { style: { width: '32rpx', height: '44rpx', position: 'relative' },
     classList: [],
     color: '#ffffff',
     name: 'success',
     size: 42,
     src: 'https://main.qcloudimg.com/raw/ca83370d449050fc5f5d6ba730670c93.png',
     _parentId: 'id166',
     _order: 1,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id167: 
   { style: 
      { marginBottom: '48rpx',
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row' },
     classList: [ 'indexModel-index-entext-content' ],
     title: '',
     _parentId: 'id165',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id172: 
   { style: {},
     classList: [ 'indexModel-index-picture-entext' ],
     decode: false,
     level: '0',
     maxLines: 2,
     selectable: false,
     space: '',
     text: 'Fill in the information',
     textAlign: 'left',
     textColor: '#878d96',
     userSelect: true,
     _parentId: 'id167',
     _order: 1,
     widgetType: 'gsd-h5-react:Text' },
  id188: 
   { style: {},
     classList: [],
     contentSlot: '',
     formType: 'create',
     initialValues: {},
     layout: 'horizontal',
     varPath: '',
     _parentId: 'id148',
     _order: 5,
     widgetType: 'CLOUDBASE_STANDARD:Form' },
  id189: 
   { style: 
      { color: 'rgb(255, 255, 255)',
        fontSize: '316pt',
        fontFamily: 'PingFang-SC-Regular' },
     classList: [ 'form-margin', 'indexModel-formTitle' ],
     adjustPosition: true,
     alwaysEmbed: false,
     autoFill: '',
     clearable: true,
     confirmHold: false,
     confirmType: 'done',
     cursor: -1,
     cursorSpacing: 0,
     descSlot: '',
     focus: false,
     holdKeyboard: false,
     label: '姓名',
     labelSlot: '',
     labelVisible: true,
     layout: 'vertical',
     maxLength: 140,
     name: 'name',
     password: false,
     placeholder: '',
     required: true,
     requiredFlag: true,
     requiredMsg: '该项为必填项',
     rules: [],
     selectionEnd: -1,
     selectionStart: -1,
     size: 'l',
     type: 'text',
     underline: false,
     validateStatus: 'success',
     validateTrigger: 'onBlur',
     _parentId: 'id188',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:FormInput' },
  id190: 
   { style: {},
     classList: [ 'form-margin', 'indexModel-formTitle' ],
     adjustPosition: true,
     alwaysEmbed: false,
     autoFill: '',
     clearable: true,
     confirmHold: false,
     confirmType: 'done',
     cursor: -1,
     cursorSpacing: 0,
     descSlot: '',
     focus: false,
     holdKeyboard: false,
     label: '手机号',
     labelSlot: '',
     labelVisible: true,
     layout: 'vertical',
     maxLength: 11,
     name: 'phone',
     password: false,
     placeholder: '',
     required: true,
     requiredFlag: true,
     requiredMsg: '该项为必填项',
     rules: 
      [ { format: 'mobile',
          message: '请填写正确手机号',
          pattern: '/^1([358][0-9]|4[579]|66|7[0135678]|9[89])[0-9]{8}$/' } ],
     selectionEnd: -1,
     selectionStart: -1,
     size: 'l',
     type: 'number',
     underline: false,
     validateStatus: 'success',
     validateTrigger: 'onBlur',
     _parentId: 'id188',
     _order: 1,
     widgetType: 'CLOUDBASE_STANDARD:FormInput' },
  id191: 
   { style: {},
     classList: [ 'form-margin', 'indexModel-formTitle' ],
     adjustPosition: true,
     alwaysEmbed: false,
     autoFill: '',
     clearable: true,
     confirmHold: false,
     confirmType: 'done',
     cursor: -1,
     cursorSpacing: 0,
     descSlot: '',
     focus: false,
     holdKeyboard: false,
     label: '参会人数',
     labelSlot: '',
     labelVisible: true,
     layout: 'vertical',
     maxLength: 140,
     name: 'joinNumber',
     password: false,
     placeholder: '',
     required: true,
     requiredFlag: true,
     requiredMsg: '该项为必填项',
     rules: [ { format: 'num', message: '请填写数字' } ],
     selectionEnd: -1,
     selectionStart: -1,
     size: 'l',
     type: 'number',
     underline: false,
     validateStatus: 'success',
     validateTrigger: 'onChange',
     _parentId: 'id188',
     _order: 2,
     widgetType: 'CLOUDBASE_STANDARD:FormInput' },
  id192: 
   { style: {},
     classList: [ 'form-margin', 'indexModel-formTitle' ],
     adjustPosition: true,
     alwaysEmbed: false,
     autoFill: '',
     clearable: true,
     confirmHold: false,
     confirmType: 'done',
     cursor: -1,
     cursorSpacing: 0,
     descSlot: '',
     focus: false,
     holdKeyboard: false,
     label: '公司名称',
     labelSlot: '',
     labelVisible: true,
     layout: 'vertical',
     maxLength: 140,
     name: 'unitName',
     password: false,
     placeholder: '',
     required: true,
     requiredFlag: true,
     requiredMsg: '该项为必填项',
     rules: [],
     selectionEnd: -1,
     selectionStart: -1,
     size: 'l',
     type: 'text',
     underline: false,
     validateStatus: 'success',
     validateTrigger: 'onChange',
     _parentId: 'id188',
     _order: 3,
     widgetType: 'CLOUDBASE_STANDARD:FormInput' },
  id193: 
   { style: {},
     classList: [ 'form-margin', 'indexModel-formTitle' ],
     adjustPosition: true,
     alwaysEmbed: false,
     autoFill: '',
     clearable: true,
     confirmHold: false,
     confirmType: 'done',
     cursor: -1,
     cursorSpacing: 0,
     descSlot: '',
     focus: false,
     holdKeyboard: false,
     label: '微信号',
     labelSlot: '',
     labelVisible: true,
     layout: 'vertical',
     maxLength: 140,
     name: 'wxNumber',
     password: false,
     placeholder: '',
     required: true,
     requiredFlag: true,
     requiredMsg: '该项为必填项',
     rules: [],
     selectionEnd: -1,
     selectionStart: -1,
     size: 'l',
     type: 'text',
     underline: false,
     validateStatus: 'success',
     validateTrigger: 'onChange',
     _parentId: 'id188',
     _order: 4,
     widgetType: 'CLOUDBASE_STANDARD:FormInput' },
  id195: 
   { style: { height: '410rpx' },
     classList: [],
     title: '',
     _parentId: 'id188',
     _order: 8,
     widgetType: 'gsd-h5-react:Container' },
  id196: 
   { style: 
      { display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row' },
     classList: [ 'indexModel-index-picture-content' ],
     title: '',
     _parentId: 'id195',
     _order: 0,
     widgetType: 'gsd-h5-react:Container' },
  id198: 
   { style: {},
     classList: [ 'indexModel-index-picture-text' ],
     decode: false,
     level: '0',
     maxLines: 2,
     selectable: false,
     space: '',
     text: '会议地址',
     textAlign: 'left',
     textColor: 'rgb(255,255,255)',
     userSelect: true,
     _parentId: 'id196',
     _order: 1,
     widgetType: 'gsd-h5-react:Text' },
  id199: 
   { style: { width: '32rpx', height: '44rpx', position: 'relative' },
     classList: [],
     color: '#ffffff',
     name: 'success',
     size: 42,
     src: 'https://main.qcloudimg.com/raw/ca83370d449050fc5f5d6ba730670c93.png',
     _parentId: 'id196',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id211: 
   { style: 
      { height: '60rpx',
        marginTop: '40rpx',
        marginRight: '32rpx',
        marginLeft: '38rpx',
        display: 'flex',
        alignItems: 'center',
        flexDirection: 'row',
        fontSize: '14rpx' },
     classList: [ 'indexModel-content-info-content' ],
     title: '',
     _parentId: 'id195',
     _order: 2,
     widgetType: 'gsd-h5-react:Container' },
  id212: 
   { style: { width: '40rpx', height: '60rpx', verticalAlign: 'middle' },
     classList: [],
     color: '',
     name: 'success',
     size: 48,
     src: 'https://main.qcloudimg.com/raw/6d16619dcc299d82a8028aff16ce0b09.png',
     _parentId: 'id211',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id224: 
   { style: { width: '70%' },
     classList: [ 'indexModel-content-info-text' ],
     title: '',
     _parentId: 'id211',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id213: 
   { style: {},
     classList: [],
     decode: false,
     maxLines: 2,
     selectable: false,
     space: '',
     text: '深圳市南山区深南大道10000号',
     userSelect: true,
     _parentId: 'id224',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id226: 
   { style: 
      { padding: '10rpx 20rpx 14rpx',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column',
        position: 'absolute',
        right: '30rpx' },
     classList: [],
     title: '',
     _parentId: 'id211',
     _order: 3,
     widgetType: 'gsd-h5-react:Container' },
  id225: 
   { style: 
      { display: 'flex',
        justifyContent: 'center',
        color: 'rgb(193, 199, 205)',
        fontFamily: 'PingFangSC-Regular',
        verticalAlign: 'middle' },
     classList: [],
     color: '#C1C7CD',
     name: 'success',
     size: 40,
     src: 'https://main.qcloudimg.com/raw/914fe48cb6d5b839ecf2042dad3ceaeb.png',
     _parentId: 'id226',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id227: 
   { style: { color: '#A2A9B0', fontSize: '22rpx' },
     classList: [],
     decode: false,
     level: '0',
     maxLines: 1,
     selectable: false,
     space: '',
     text: '到这里',
     textAlign: 'left',
     textColor: '#A2A9B0',
     userSelect: true,
     _parentId: 'id226',
     _order: undefined,
     widgetType: 'gsd-h5-react:Text' },
  id197: 
   { style: 
      { marginBottom: '48rpx',
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row' },
     classList: [ 'indexModel-index-entext-content' ],
     title: '',
     _parentId: 'id195',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id200: 
   { style: {},
     classList: [ 'indexModel-index-picture-entext' ],
     decode: false,
     level: '0',
     maxLines: 2,
     selectable: false,
     space: '',
     text: 'Address guidelines',
     textAlign: 'left',
     textColor: '#878d96',
     userSelect: true,
     _parentId: 'id197',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id194: 
   { style: {},
     classList: [ 'checkbox-group', 'indexModel-formTitle' ],
     descSlot: '',
     label: '您希望了解的（多选）',
     labelSlot: '',
     labelVisible: true,
     layout: 'vertical',
     name: 'hopeTo',
     range: 
      [ { label: '价格合适', value: 'first' },
        { label: '自己喜欢的都愿意推荐', value: 'second' },
        { label: '推荐成功有优惠', value: 'third' },
        { label: '从不推荐，怕麻烦别人', value: 'fourth' } ],
     required: true,
     requiredFlag: true,
     requiredMsg: '该项为必填项',
     underline: false,
     validateStatus: 'success',
     validateTrigger: 'onChange',
     value: [],
     _parentId: 'id188',
     _order: 5,
     widgetType: 'CLOUDBASE_STANDARD:FormCheckbox' },
  id214: 
   { style: {},
     classList: [ 'indexModel-btn-content' ],
     title: '',
     _parentId: 'id188',
     _order: 9,
     widgetType: 'gsd-h5-react:Container' },
  id210: 
   { style: {},
     classList: [ 'indexModel-submitbtn' ],
     appParameter: '',
     categoryId: [],
     content: '提交',
     contentSlot: '',
     disabled: false,
     formType: 'submit',
     loading: false,
     openType: '',
     plain: false,
     sendMessageImg: '',
     sendMessagePath: '',
     sendMessageTitle: '',
     sessionFrom: '',
     showMessageCard: '',
     size: 'default',
     type: 'primary',
     _parentId: 'id214',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:Button' },
  id229: 
   { style: { display: 'flex' },
     classList: [],
     _parentId: 'id188',
     _order: 6,
     widgetType: 'gsd-h5-react:Container' },
  id230: 
   { style: 
      { margin: '5rpx -86rpx 0rpx 0rpx',
        paddingTop: '10rpx',
        paddingBottom: '0rpx',
        paddingLeft: '0rpx',
        display: 'block' },
     classList: [ 'checkbox-box' ],
     disabled: false,
     label: '复选框',
     labelVisible: false,
     layout: '',
     name: 'confirm',
     range: [ { label: '', value: 'true' } ],
     required: false,
     requiredFlag: '',
     requiredMsg: '该项为必填项',
     value: [],
     _parentId: 'id229',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:FormCheckbox' },
  id231: 
   { style: { display: 'flex', alignItems: 'center' },
     classList: [],
     _parentId: 'id229',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id232: 
   { style: { color: 'white', fontSize: '26rpx', whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 2,
     space: false,
     text: '我已阅读并同意',
     textAlign: 'left',
     textColor: 'white',
     userSelect: true,
     _parentId: 'id231',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id233: 
   { style: 
      { color: 'rgb(98, 169, 232)',
        fontSize: '26rpx',
        whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 2,
     space: false,
     text: '《隐私政策》',
     textAlign: 'left',
     textColor: 'rgb(98, 169,232)',
     userSelect: true,
     _parentId: 'id231',
     _order: 3,
     widgetType: 'gsd-h5-react:Text' },
  id234: 
   { style: 
      { color: 'rgb(98, 169, 232)',
        fontSize: '26rpx',
        whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 2,
     space: false,
     text: '《用户服务协议》',
     textAlign: 'left',
     textColor: 'rgb(98, 169,232)',
     userSelect: true,
     _parentId: 'id231',
     _order: 1,
     widgetType: 'gsd-h5-react:Text' },
  id235: 
   { style: 
      { color: 'rgb(255, 255, 255)',
        fontSize: '26rpx',
        whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 2,
     space: false,
     text: '及',
     textAlign: 'left',
     textColor: 'white',
     userSelect: true,
     _parentId: 'id231',
     _order: 2,
     widgetType: 'gsd-h5-react:Text' },
  id236: 
   { style: 
      { marginBottom: '34rpx',
        paddingRight: '60rpx',
        paddingLeft: '60rpx' },
     classList: [],
     _parentId: 'id188',
     _order: 7,
     widgetType: 'gsd-h5-react:Container' },
  id237: 
   { style: 
      { color: 'rgb(255, 84, 77)',
        fontSize: '28rpx',
        whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 20,
     space: false,
     text: '附件《用户服务协议》及《隐私政策》为腾讯提供的参考模板。使用者应根据国家法律法规要求，结合提供的产品和服务实际情况进行修改或另行使用其他协议模板。腾讯不对《用户服务协议》及《隐私政策》模板的完整性、准确性以及适用性进行任何承诺。还请使用者甄别使用！',
     textAlign: 'left',
     textColor: '#FF544D',
     userSelect: true,
     _parentId: 'id236',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id222: 
   { style: {},
     classList: [ 'indexModel-content-bgone' ],
     color: '',
     name: 'success',
     size: 300,
     src: 'https://main.qcloudimg.com/raw/07dd595d61598a89bacee3c2f10cdc43.png',
     _parentId: 'id148',
     _order: 0,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id223: 
   { style: {},
     classList: [ 'indexModel-content-bgtwo' ],
     color: '',
     name: 'success',
     size: 300,
     src: 'https://main.qcloudimg.com/raw/21895ee76977b7f73ae7294e1bee47db.png',
     _parentId: 'id148',
     _order: 1,
     widgetType: 'CLOUDBASE_STANDARD:Icon' },
  id238: 
   { style: {},
     classList: [],
     _parentId: 'id148',
     _order: 6,
     widgetType: 'gsd-h5-react:Container' },
  id239: 
   { style: { zIndex: '99' },
     classList: [],
     content: '',
     isDefaultButton: false,
     _parentId: 'id238',
     _order: undefined,
     widgetType: 'CLOUDBASE_STANDARD:Modal' },
  id240: 
   { style: {},
     classList: [],
     _parentId: 'id239',
     _order: 1,
     widgetType: 'gsd-h5-react:Container' },
  id242: 
   { style: { fontSize: '32rpx', fontWeight: '700', whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 2,
     space: true,
     text: 'XX服务协议',
     textAlign: 'left',
     textColor: 'rgb(0, 0, 0)',
     userSelect: true,
     _parentId: 'id240',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id243: 
   { style: { height: '1000rpx' },
     classList: [],
     bounces: true,
     enableBackToTop: false,
     enableFlex: false,
     enhanced: true,
     fastDeceleration: true,
     lowerThreshold: 50,
     pagingEnabled: false,
     refresherBackground: '#fff',
     refresherDefaultStyle: 'block',
     refresherEnabled: false,
     refresherThreshold: 50,
     refresherTriggered: '',
     scrollAnchoring: false,
     scrollIntoView: '',
     scrollLeft: '',
     scrollTop: '',
     scrollWithAnimation: false,
     scrollX: false,
     scrollY: true,
     showScrollbar: true,
     upperThreshold: 50,
     _parentId: 'id240',
     _order: 2,
     widgetType: 'gsd-h5-react:ScrollView' },
  id244: 
   { style: { marginTop: '40rpx', whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 1340,
     space: true,
     text: '【首部及导言】 \n\n欢迎您使用XX的服务！ \n\n        为使用xx的服务，您应当阅读并遵守《xx服务协议》（以下简称“本协议”）和《xx隐私政策》。请您务必审慎阅读、充分理解各条款内容，特别是免除或者限制xx责任的条款、对用户权利进行限制的条款、约定争议解决方式和司法管辖的条款（如第十八条相关约定）等，以及开通或使用某项服务的单独协议或规则。限制、免责条款或者其他涉及您重大权益的条款可能以加粗、加下划线等形式提示您重点注意。 \n\n        除非您已充分阅读、完全理解并接受本协议所有条款，否则您无权使用xx服务。您点击“同意”或“下一步”，或您使用xx服务，或者以其他任何明示或者默示方式表示接受本协议的，均视为您已阅读并同意签署本协议。本协议即在您与xx之间产生法律效力，成为对双方均具有约束力的法律文件。 \n        \n        如果您因年龄、智力等因素而不具有完全民事行为能力，请在法定监护人（以下简称"监护人"）的陪同下阅读和判断是否同意本协议，并特别注意未成年人使用条款。 \n        \n        如果您是中国大陆地区以外的用户，您订立或履行本协议还需要同时遵守您所属和/或所处国家或地区的法律。\n\n一、【协议的范围】\n\n      1.1本协议是用户与xx之间关于其使用xx的服务所订立的协议。“xx”是指xx和/或其相关服务可能存在的运营关联单位。“用户”是指xx的服务的使用人，在本协议中更多地称为“您”。\n\n      1.2xx的服务是指xx向用户提供的，包括但不限于即时通讯、网络媒体、互联网增值、互动娱乐、金融支付、广告等产品及服务，具体服务以xx实际提供的为准（以下简称“本服务”）。\n\n      1.3本协议内容同时包括《xx隐私政策》,且您在使用xx某一特定服务时，该服务可能会另有单独的协议、相关业务规则等（以下统称为“单独协议”）。上述内容一经正式发布，即为本协议不可分割的组成部分，您同样应当遵守。您对前述任何单独协议的接受，即视为您对本协议全部的接受。您对本协议的接受，即视为您对《xx隐私政策》的接受。\n\n二、【帐号与密码安全】\n\n      2.1您在使用本服务时可能需要注册一个帐号。关于您使用帐号的具体规则，请仔细阅读并遵守相关单独协议。\n\n      2.2xx特别提醒您应妥善保管您的帐号和密码。当您使用完毕后，应安全退出。因您保管不善可能导致遭受被盗号或密码失窃，责任由您自行承担。\n\n2.3为增强用户体验和/或技术便利，本服务的帐号可能包括数字、字母或者其组合，以及手机号码、电子信箱等多种形式。在您注册某一形式的帐号时，xx可能附赠该帐号的另一表现形式。具体的帐号形式、帐号体系及帐号之间的关联关系等，以xx实际提供的为准。\n\n      2.4您在使用本服务过程中，可能可以为您使用的帐号设置昵称、头像、签名、留言等信息，也可能为您建立或者管理、参与的QQ群、微信群等设置名称、图片、简介等信息。您应当保证这些信息的内容和形式符合法律法规（本协议中的“法律法规”指用户所属/所处地区、国家现行有效的法律、行政法规、司法解释、地方法规、地方规章、部门规章及其他规范性文件以及对于该等法律法规的不时修改和补充，以及相关政策规定等，下同。）、公序良俗、社会公德以及xx平台规则，且不会侵害任何主体的合法权益。\n\n      2.5部分第三方网站或者服务可能可以用QQ帐号、微信帐号等作为其登录途径之一。您知晓，除非xx特别说明外，这些网站或者服务并非xx运营，您应自行判断此类第三方网站或者服务的安全性和可用性，并自行承担相关风险和责任。\n\n三、【用户个人信息保护】\n\n      3.1保护用户个人信息是xx的一项基本原则。xx将按照本协议及《xx隐私政策》的规定收集、使用、储存和分享您的个人信息。本协议对个人信息保护相关内容未作明确规定的，均应以《xx隐私政策》的内容为准。\n\n      3.2您在注册帐号或使用本服务的过程中，可能需要填写一些必要的信息。若国家法律法规有特殊规定的，您需要填写真实的身份信息。若您填写的信息不完整，则可能无法使用本服务或在使用过程中受到限制。\n\n      3.3一般情况下，您可根据相关产品规则浏览、修改自己提交的信息，但出于安全性和身份识别（如号码申诉服务等）的考虑，您可能无法修改注册时提供的初始注册信息及其他验证信息。\n\n      3.4xx将尽可能运用各种安全技术和程序建立完善的管理制度来保护您的个人信息，以免遭受未经授权的访问、使用或披露。\n\n      3.5xx不会将您的个人信息转移或披露给任何第三方，除非：\n\n      （1）相关法律法规或司法机关、行政机关要求。\n\n      （2）为完成合并、分立、收购或资产转让而转移。\n\n      （3）为提供您要求的服务所必需。\n\n      （4）依据《xx隐私政策》或其他相关协议规则可以转移或披露给任何第三方的情形。\n\n     3.6xx非常重视对未成年人个人信息的保护。若您不具备完全民事行为能力，在使用xx的服务前，应事先取得您的监护人的同意。\n\n四、【使用本服务的方式】\n\n     4.1本服务仅为您个人非商业性质的使用，除非您与xx另有约定。\n\n     4.2您依本协议条款所取得的权利不可转让。\n\n     4.3您不得使用任何方式（包括但不限于第三方软件、插件、外挂、系统、设备等）对本服务进行干扰、破坏、修改或施加其他影响。\n\n     4.4您应当通过xx提供或认可的方式使用本服务，不得通过任何第三方软件、插件、外挂、系统、设备等登录或使用本服务。\n\n     4.5任何人未经xx授权不得使用任何第三方软件、插件、外挂、系统等查看、获取本服务中所包含的xx、xx合作伙伴或用户的任何相关信息、数据等内容，同时，应当严格遵守xx发布的Robots协议等相关协议规则。\n\n五、【按现状提供服务】\n\n您理解并同意：\n\n     5.1本服务是按照现有技术和条件所能达到的现状提供的。xx会尽最大努力保障服务的连贯性和安全性，但xx不能随时预见和防范法律、技术以及其他风险，xx对此类风险在法律允许的范围内免责，包括但不限于不可抗力、病毒、木马、黑客攻击、系统不稳定、第三方服务瑕疵、政府行为等原因可能导致的服务中断、数据丢失以及其他的损失和风险。\n\n     5.2因经营策略安排或调整等原因,不同地区的用户可使用的具体xx服务的内容可能会存在差异，具体以xx实际提供的为准。\n\n六、【自备设备】\n\n     6.1您应当理解，您使用本服务需自行准备与相关服务有关的终端设备（如电脑、移动终端和必要的网络接入设备等装置），并承担所需的费用（如电话费、上网费等费用）。\n\n     6.2您理解并同意，您使用本服务时会耗用您的终端设备和带宽等资源。\n\n七、【广告】\n\n     7.1您同意xx可以自行或由第三方通过短信、电子邮件或电子信息等多种方式向您发送、展示广告或其他信息（包括商业与非商业信息），广告或其他信息的具体发送及展示形式、频次及内容等以xx实际提供为准。\n\n     7.2xx将依照相关法律法规要求开展广告业务。您同意，对本服务中出现的广告，您应审慎判断其真实性和可靠性，除法律明确规定外，您应对因该广告而实施的行为负责。\n\n八、【服务费用】\n\n     8.1xx的部分服务是以收费方式提供的，如您使用收费服务，请遵守相关的协议。\n\n     8.2xx可能根据实际需要对收费服务的收费标准、方式进行修改和变更，xx也可能会对部分免费服务开始收费。前述修改、变更或开始收费前，xx将在相应服务页面进行通知或公告。如果您不同意上述修改、变更或付费内容，则应停止使用该服务。\n\n     8.3在xx降低收费服务的收费标准或者将收费服务改为免费服务提供时，xx保留不对原付费用户提供退费或者费用调整之权利。\n\n九、【第三方提供的产品或服务】\n\n     您在xx平台上使用第三方提供的产品或服务时，除遵守本协议约定外，还应遵守第三方的用户协议。xx和第三方对可能出现的纠纷在法律规定和约定的范围内各自承担责任。\n\n十、【基于软件提供服务】\n\n若xx依托“软件”向您提供服务，您还应遵守以下约定：\n\n     10.1您在使用本服务的过程中可能需要下载软件，对于这些软件，xx给予您一项个人的、不可转让及非排他性的许可。您仅可为使用本服务的目的而使用这些软件。\n\n     10.2为了改善用户体验、保障服务的安全性及产品功能的一致性等目的，xx可能会对软件进行更新。您应该将相关软件更新到最新版本，否则xx并不保证软件或服务能正常使用。\n\n     10.3xx可能为不同的终端设备开发不同的软件版本，您应当根据实际情况选择下载合适的版本进行安装。您可以直接从xx平台上获取软件，也可以从得到xx授权的第三方获取。如果您从未经xx授权的第三方获取软件或与软件名称相同的安装程序，xx无法保证该软件或服务能够正常使用，并对因此给您造成的损失不予负责。\n\n     10.4除非xx书面许可，您不得从事下列任一行为：\n\n     （1）删除软件及其副本上关于著作权的信息。\n\n     （2）对软件进行反向工程、反向汇编、反向编译，或者以其他方式尝试发现软件的源代码。\n\n     （3）对xx拥有知识产权的内容进行使用、出租、出借、复制、修改、链接、转载、汇编、发表、出版、建立镜像站点等。\n\n     （4）对软件或者软件运行过程中释放到任何终端内存中的数据、软件运行过程中客户端与服务器端的交互数据，以及软件运行所必需的系统数据，进行复制、修改、增加、删除、挂接运行或创作任何衍生作品，形式包括但不限于使用插件、外挂或非经xx授权的第三方工具/服务接入软件和相关系统。\n\n     （5）通过修改或伪造软件运行中的指令、数据等任何方式，增加、删减、变动软件的功能或运行效果，或者将用于上述用途的软件、方法进行运营或向公众传播，无论这些行为是否为商业目的。\n\n     （6）通过非xx开发、授权的第三方软件、插件、外挂、系统、设备等任何方式，登录或使用xx软件及服务，或制作、发布、传播非xx开发、授权的用于登录或使用xx软件及服务的第三方软件、插件、外挂、系统、设备等。\n\n十一、【知识产权声明】\n\n     11.1xx在本服务中提供的内容（包括但不限于网页、文字、图片、音频、视频、图表、计算机软件等）的知识产权归xx所有，用户在使用本服务中所产生内容的知识产权归用户或相关权利人所有，除非您与xx另有约定。\n\n     11.2除另有特别声明外，xx提供本服务时所依托软件的著作权、专利权及其他知识产权均归xx所有。\n\n     11.3xx在本服务中所使用的“xx”商业标识，其著作权或商标权归xx所有。\n\n     11.4上述及其他任何本服务包含的内容的知识产权均受到法律法规保护，未经xx、用户或相关权利人书面许可，任何人不得以任何形式进行使用或创造相关衍生作品。\n\n十二、【用户违法违规行为】\n\n     12.1您在使用本服务时须遵守法律法规，不得制作、复制、发布、传播含有下列内容的信息或从事相关行为，也不得为制作、复制、发布、传播含有下列内容的信息或从事相关行为提供便利：\n\n     （1）反对宪法所确定的基本原则的。\n\n     （2）危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的。\n\n     （3）损害国家荣誉和利益的。\n\n     （4）煽动民族仇恨、民族歧视，破坏民族团结的。\n\n     （5）破坏国家宗教政策，宣扬邪教和封建迷信的。\n\n     （6）散布谣言，扰乱社会秩序，破坏社会稳定的。\n\n     （7）散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的。\n\n     （8）侮辱或者诽谤他人，侵害他人合法权益的。\n\n     （9）违反法律法规底线、社会主义制度底线、国家利益底线、公民合法权益底线、社会公共秩序底线、道德风尚底线和信息真实性底线的“七条底线”要求的。\n\n     （10）相关法律法规或本协议、相关协议、规则等禁止的。\n\n     12.2如果您在使用本服务过程中违反了相关法律法规或本协议约定，相关国家机关或机构可能会对您提起诉讼、罚款或采取其他制裁措施，并要求xx给予协助。因此给您或者他人造成损害的，您应自行承担全部责任，xx不承担任何责任。\n\n     12.3如果您违反本协议约定，xx有权进行独立判断并采取相应措施，包括但不限于通过技术手段删除、屏蔽相关内容或断开链接等。同时，xx有权视用户的行为性质，采取包括但不限于暂停或终止向您提供服务，限制、中止、冻结或终止您对QQ帐号、微信帐号的使用，追究法律责任等措施。\n\n     12.4您违反本协议约定，导致任何主体损失的，您应当独立承担责任；xx因此遭受损失的，您也应当一并赔偿。\n\n十三、【遵守当地法律监管】\n\n    13.1您在使用本服务过程中应当遵守当地相关的法律法规，并尊重当地的道德和风俗习惯。如果您的行为违反了当地法律法规或道德风俗，您应当为此独立承担责任。\n\n    13.2您应避免因使用本服务而使xx违反法律法规或卷入政治和公共事件，否则xx有权暂停或终止对您的服务。\n\n十四、【用户发送、传播的内容与投诉处理】\n\n    14.1您通过本服务发送或传播的内容（包括但不限于网页、文字、图片、音频、视频、图表等）均由您自行承担责任。\n\n    14.2您发送或传播的内容应有合法来源，相关内容为您所有或您已获得必要的授权。\n\n    14.3如果您发送或传播的内容违法违规或侵犯他人权利的，xx有权进行独立判断并采取删除、屏蔽或断开链接等措施。\n\n    14.4如您被他人投诉或您投诉他人，xx有权将争议中相关方的主体信息、联系方式、投诉相关内容等必要信息提供给相关当事方或相关部门，以便及时解决投诉纠纷，保护各方合法权益。\n\n    14.5您保证对您在投诉处理程序中提供的信息、材料、证据等的真实性、合法性、有效性负责。\n\n十五、【不可抗力及其他免责事由】\n\n    15.1您理解并同意，在使用本服务的过程中，可能会遇到不可抗力等风险因素，使本服务受到影响。不可抗力是指不能预见、不能克服并不能避免且对一方或双方造成重大影响的客观事件，包括但不限于自然灾害如洪水、地震、瘟疫流行和风暴等以及社会事件如战争、动乱、政府行为等。出现上述情况时，xx将努力在第一时间与相关单位配合，争取及时进行处理，但是由此给您造成的损失xx在法律允许的范围内免责。\n\n    15.2在法律允许的范围内，xx对以下情形导致的服务中断或受阻不承担责任：\n\n    （1）受到计算机病毒、木马或其他恶意程序、黑客攻击的破坏。\n\n    （2）用户或xx的电脑软件、系统、硬件和通信线路出现故障。\n\n    （3）用户操作不当或用户通过非xx授权的方式使用本服务。\n\n    （4）程序版本过时、设备的老化和/或其兼容性问题。\n\n    （5）其他xx无法控制或合理预见的情形。\n\n    15.3您理解并同意，在使用本服务的过程中，可能会遇到网络信息或其他用户行为带来的风险，xx不对任何信息的真实性、适用性、合法性承担责任，也不对因侵权行为给您造成的损害负责。这些风险包括但不限于：\n\n    （1）来自他人匿名或冒名的含有威胁、诽谤、令人反感或非法内容的信息。\n\n    （2）遭受他人误导、欺骗或其他导致或可能导致的任何心理、生理上的伤害以及经济上的损失。\n\n    （3）其他因网络信息或用户行为引起的风险。\n\n    15.4xx依据本协议约定获得处理违法违规内容的权利，该权利不构成xx的义务或承诺，xx不能保证及时发现违法行为或进行相应处理。\n\n15.5在任何情况下，您不应轻信借款、索要密码或其他涉及财产的信息。涉及财产操作的，请一定先核实对方身份，并请经常留意xx有关防范诈骗犯罪的提示。\n\n十六、【协议的生效与变更】\n\n    16.1您使用本服务即视为您已阅读本协议并接受本协议的约束。\n\n    16.2xx有权在必要时修改本协议条款。您可以在相关服务页面查阅最新版本的协议条款。\n\n    16.3本协议条款变更后，如果您继续使用xx提供的软件或服务，即视为您已接受变更后的协议。\n\n十七、【服务的变更、中断、终止】\n\n    17.1您理解并同意，xx基于经营策略的调整，可能会对服务内容进行变更，也可能会中断、中止或终止服务。\n\n    17.2在xx发生合并、分立、收购、资产转让时，xx可向第三方转让本服务下相关资产；xx也可在单方通知您后，将本协议下部分或全部服务及相应的权利义务转交由第三方运营或履行。具体受让主体以xx通知的为准。\n\n    17.3如发生下列任何一种情形，xx有权不经通知而中断或终止向您提供服务：\n\n    （1）根据法律法规规定您应提交真实信息，而您提供的个人资料不真实、或与注册时信息不一致又未能提供合理证明。\n\n    （2）您违反相关法律法规的规定或违反本协议的约定。\n\n    （3）按照法律法规规定，司法机关或主管部门的要求。\n\n    （4）出于安全的原因或其他必要的情形。\n\n    17.4xx有权按本协议8.2条的约定进行收费。若您未按时足额付费，xx有权中断、中止或终止提供服务。\n\n    17.5您有责任自行备份存储在本服务中的数据。如果您的服务被终止，xx有权从服务器上永久地删除您的数据,法律法规另有规定的除外。服务中止或终止后，xx没有义务向您提供或返还数据。\n\n十八、【管辖与法律适用】\n\n    18.1本协议的成立、生效、履行、解释及纠纷解决等相关事宜，均适用中华人民共和国大陆地区法律（不包括冲突法）。\n\n    18.2本协议签订地为中华人民共和国广东省深圳市南山区。\n\n    18.3若您和xx之间发生任何纠纷或争议，首先应友好协商解决；协商不成的，您同意将纠纷或争议提交本协议签订地（即中国广东省深圳市南山区）有管辖权的人民法院管辖。\n\n    18.4本协议所有条款的标题仅为阅读方便，本身并无实际涵义，不能作为本协议涵义解释的依据。\n\n    18.5本协议条款无论因何种原因部分无效或不可执行，其余条款仍有效，对双方具有约束力。\n\n    18.6若本协议有中文、英文等多个语言版本，相应内容不一致的，均以中文版的内容为准。\n\n十九、【未成年人使用条款】\n\n    19.1若用户未满18周岁，则为未成年人，应在监护人监护、指导下阅读本协议和使用本服务。\n\n    19.2未成年人用户涉世未深，容易被网络虚像迷惑，且好奇心强，遇事缺乏随机应变的处理能力，很容易被别有用心的人利用而又缺乏自我保护能力。因此，未成年人用户在使用本服务时应注意以下事项，提高安全意识，加强自我保护：\n\n    （1）认清网络世界与现实世界的区别，避免沉迷于网络，影响日常的学习生活。\n\n    （2）填写个人资料时，加强个人保护意识，以免不良分子对个人生活造成骚扰。\n\n    （3）在监护人或老师的指导下，学习正确使用网络。\n\n    （4）避免陌生网友随意会面或参与联谊活动，以免不法分子有机可乘，危及自身安全。\n\n    19.3监护人、学校均应对未成年人使用本服务多做引导。特别是家长应关心子女的成长，注意与子女的沟通，指导子女上网应该注意的安全问题，防患于未然。\n\n    19.4已满18周岁的成年人因任何原因不具备完全民事行为能力的，参照适用本协议之未成年人使用条款之相关约定。\n\n二十、【其他】\n\n    20.1如果您对本协议或本服务有意见或建议，可与xx客户服务部门联系（kf.xx.com），我们会给予您必要的帮助。（正文完）\n\n\nxx公司\n\n',
     textAlign: 'left',
     textColor: 'rgb(0, 0, 0)',
     userSelect: true,
     _parentId: 'id243',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id241: 
   { style: {},
     classList: [],
     _parentId: 'id239',
     _order: undefined,
     widgetType: 'gsd-h5-react:Container' },
  id245: 
   { style: { fontSize: '32rpx', fontWeight: '700', whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 2,
     space: false,
     text: '【小程序名称】隐私保护指引\n',
     textAlign: 'left',
     textColor: 'rgb(0, 0, 0)',
     userSelect: true,
     _parentId: 'id241',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' },
  id246: 
   { style: { height: '1000rpx' },
     classList: [],
     bounces: true,
     enableBackToTop: false,
     enableFlex: false,
     enhanced: true,
     fastDeceleration: true,
     lowerThreshold: 50,
     pagingEnabled: false,
     refresherBackground: '#fff',
     refresherDefaultStyle: 'block',
     refresherEnabled: false,
     refresherThreshold: 50,
     refresherTriggered: '',
     scrollAnchoring: false,
     scrollIntoView: '',
     scrollLeft: '',
     scrollTop: '',
     scrollWithAnimation: false,
     scrollX: false,
     scrollY: true,
     showScrollbar: true,
     upperThreshold: 50,
     _parentId: 'id241',
     _order: 2,
     widgetType: 'gsd-h5-react:ScrollView' },
  id247: 
   { style: { marginTop: '40rpx', whiteSpace: 'pre-line' },
     classList: [],
     level: '0',
     maxLines: 1340,
     space: true,
     text: '生效日期： 2021年 11 月 16 日\n\n\n概要\n欢迎您使用【小程序名称】服务！\n\n【小程序名称】提供小程序线上商城服务（以下简称“本服务”），我们将通过《【小程序名称】隐私保护指引》（以下简称“本指引”）帮助您了解我们收集、使用、存储和共享个人信息的情况，以及您所享有的相关权利。\n请您仔细阅读本指引（尤其是加粗的内容）并确定了解我们对您个人信息的处理规则。阅读本指引的过程中，如您有问题，请联系我们。如您理解并同意接受本指引，即可点击“同意”开始接受我们的服务。如您不同意本指引中的任何条款，请您立即停止访问和使用。\n\n本指引将帮助您了解以下内容：\n一、\t我们收集和使用的信息\n二、\t信息的存储\n三、\t信息的安全\n四、\t对外提供\n五、\t您的权利\n六、\t变更\n七、\t未成年人保护\n八、\t其他\n九、\t联系我们\n\n\n一、我们收集和使用的信息\n您在使用本服务的过程中，我们根据合法、正当、必要的原则，仅收集实现本软件功能所必要的如下个人信息：\n● 您在注册账号时填写的信息\n您可以通过登录小程序授权您本人的微信账号注册登录，并主动绑定手机号。绑定手机号是实现本服务账号实名等功能的必要信息。\n● 我们在您使用服务时获取的信息\n您在使用本服务过程中的使用记录、浏览历史、页面点击行为、设备信息等，我们会使用这些信息以便为您提供个性化推荐功能，我们也可能会存储部分信息作为服务日志信息。\n● 您在下单支付时填写的信息\n您下订单时必须填写您希望购买的商品数量、价款及支付方式、收货人、联系方式、收货地址（合同履行地点）、合同履行方式等内容。\n● 我们可能使用 Cookie 标识符及其他相关技术收集您的信息，为您提供个性化的用户体验、保障服务安全。\n● 根据相关法律法规及国家标准，以下情形中，我们可能会收集、使用您的相关个人信息无需征求您的授权同意：\n1) 与我们履行法律法规规定的义务相关的；\n2) 与国家安全、国防安全直接相关的；\n3) 与公共安全、公共卫生、重大公共利益直接相关的；\n4) 与刑事侦查、起诉、审判和判决执行等直接相关的；\n5) 出于维护您或其他个人的生命、财产等重大合法权益但又很难得到本人授权同意的；\n6) 所涉及的个人信息是您自行向社会公众公开的；\n7) 根据您要求签订和履行合同所必需的；\n8) 从合法公开披露的信息中收集个人信息的，如合法的新闻报道、政府信息公开等渠道；\n9) 维护所提供产品或服务的安全稳定运行所必需的，如发现、处置产品或服务的故障；\n10) 法律法规规定的其他情形。\n● 如我们使用您的个人信息，将超出与收集时所声称的目的及具有直接或合理关联的范围，我们将在使用前，再次向您告知并征得您的明示同意。\n● 请您理解，我们向您提供的功能和服务是不断更新和发展的，如果某一功能或服务未在前述说明中但确需收集您的信息，我们会通过更新本指引、页面提示、交互流程、线下通知等方式另行向您说明信息收集的内容、范围和目的，以征得您的同意。\n\n二、信息的存储\n1、 信息存储的方式\n我们会通过安全的方式存储您的信息，根据您所需的服务类型，提供本地存储、数据库和服务器日志存储服务。\n2、信息存储的期限\n一般而言，我们仅为实现目的所必需的最短时间存储您的信息。但在下列情况下，我们有可能因需符合法律要求，更改个人信息的存储时间：\n（1）为遵守适用的法律法规等有关规定；\n（2）为遵守法院判决、裁定或其他法律程序的规定；\n（3）为遵守相关政府机关或法定授权组织的要求；\n（4）我们有理由确信需要遵守法律法规等有关规定；\n（5）为执行相关服务协议或本指引、维护社会公共利益，为保护我们的客户、我们或关联公司、其他用户或雇员的人身财产安全或其他合法权益所合理必需的用途。\n3、信息存储的地域\n我们会按照法律法规规定，将在中国境内收集的用户个人信息存储于中国境内。目前我们不会跨境传输或存储您的个人信息。将来如需跨境传输或存储的，我们将按相关法律法规要求进行传输和存储。\n4、停止运营时的通知\n当我们的软件或服务停止运营时，我们将以邮件、电话或线下等形式通知您，并在合理的期限内删除您的个人信息或进行匿名化处理，法律法规另有规定的除外。如有需求，您可提前自行备份相关信息。\n\n三、信息的安全\n1、   安全保护措施\n（1）我们努力为您的信息安全提供保障，以防止信息的泄露、丢失、不当使用、未经授权访问和披露等。我们使用多方位的安全保护措施，以确保您的个人信息保护处于合理的安全水平，包括技术保护手段、管理制度控制、安全体系保障等诸多方面。\n（2）我们使用的技术手段包括但不限于防火墙、加密（例如SSL）、访问控制措施等。此外，我们还会不断加强本软件的安全能力，例如，我们会在您的设备本地完成部分信息加密工作，以巩固安全传输；又如，我们会对本软件的所有可执行程序引入签名方案，以预防病毒、木马等恶意程序。\n（3）我们建立了保障个人信息安全专门的管理制度、流程和组织。例如，我们严格限制访问信息的人员范围，要求他们遵守保密义务并进行审计，违反保密义务的人员会根据规定进行处罚。我们也会审查该管理制度、流程和组织，以防未经授权的人员擅自访问、使用或披露用户的信息。\n（4）我们建议您在使用本软件和服务时充分注意对个人信息的保护，我们也会提供多种安全功能来协助您保护自己的个人信息安全。\n2、    安全事件处置措施\n若发生个人信息泄露、损毁、丢失等安全事件，我们会启动应急预案，阻止安全事件扩大。安全事件发生后，我们会及时以邮件、电话或线下等形式告知您该事件的基本情况、我们即将或已经采取的处置措施和补救措施，以及我们对您的应对建议。如果难以实现逐一告知，我们将通过公告等方式发布警示。\n\n四、对外提供\n1、在某些特定的业务场景下，我们可能会使用有能力的第三方SDK来为您提供服务我们将审慎评估第三方SDK使用共享信息的目的，并要求其遵循合作协议约定。我们不会主动向第三方共享或转让您的个人信息，如存在其他共享或转让您的个人信息或您需要我们将您的个人信息共享或转让至第三方情形时，我们会通过更新本指引的方式再次征得您的明示同意。\n2、我们不会对外公开披露所收集的个人信息，如必须公开披露时，我们会向您告知此次公开披露的目的、披露信息的类型及可能涉及的敏感信息，并征得您的明示同意，法律法规另有规定除外。\n3、随着我们业务的持续发展，我们有可能进行合并、收购、资产转让等交易，我们将告知您相关情形，按照法律法规及不低于本指引所要求的标准继续保护或要求新的控制者继续保护您的个人信息。\n4、根据相关法律法规及国家标准，以下情形中，我们可能会共享、转让、公开披露个人信息无需事先征得您的授权同意：\n（1）与国家安全、国防安全直接相关的；\n（2）与公共安全、公共卫生、重大公共利益直接相关的；\n（3）与犯罪侦查、起诉、审判和判决执行等直接相关的；\n（4）出于维护个人信息主体或其他个人的生命、财产等重大合法权益但又很难得到本人同意的；\n（5）个人信息主体自行向社会公众公开个人信息的；\n（6）从合法公开披露的信息中收集个人信息的，如合法的新闻报道、政府信息公开等渠道。\n\n五、您的权利\n在您使用本服务期间，我们会为您提供相应的操作设置，以便您可以查询、更正您的相关个人信息或撤回授权，您可参考以下操作进行操作。此外，您可以通过第八条“联系我们”进行投诉举报，您的意见将会得到及时的处理。\n● 1、访问和更正您的个人信息\n除法律法规规定外，您有权随时访问和更正您的个人信息，具体包括：\n（1）您的账户信息：您可以点击“个人中心”页面的“头像”或“昵称”查阅您提交的所有个人信息账户名称，个人资料信息：个人中心---“头像”或“昵称”进入个人资料页面（具体名称以网页内容为准）。\n（2）您的收货信息：您可以通过访问“个人中心”页面的“收货地址”菜单中随时添加、导入、更改、删除您的收货地址信息（包括收货人姓名、收货地址、收货人的电话号码）。您也可以将最常用的收货地址设置为默认地址，如此，若您下次购买商品时未更改收货地址，您的商品会配送到该默认地址。\n（3）您的订单信息：您可以通过访问“个人中心”页面的“全部订单”菜单中查看“待付款”、“待收货”、“待评价”、“退款/售后”订单。\n（4）您的评论信息：您可以访问您的个人评论，或对商品进行追评，路径为：个人中心---“待评价”订单。\n● \n2、删除您的个人信息\n您在我们的产品与/服务页面中可以直接清除或删除的信息，例如收货地址信息。\n\n在以下情形中，您可以向我们提出删除个人信息的请求：\n（1）如果我们处理个人信息的行为违反法律法规；\n（2）如果我们收集、使用您的个人信息，却未征得您的同意；\n（3）如果我们处理个人信息的行为违反了与您的约定；\n（4）如果您不再使用我们的产品或服务；\n（5）如果我们终止服务及运营。若我们决定响应您的删除请求，我们还将同时通知从我们获得您的个人信息的实体，要求其及时删除，除非法律法规另有规定，或这些实体获得您的独立授权。若我们响应您的删除请求，我们不能保证立即从备份系统中删除相应的信息，但会在备份系统更新时删除这些信息。\n3、改变您授权同意的范围或撤回您的授权\n您可以通过删除信息、关闭设备功能、在【请在此处输入小程序名称】中进行隐私设置等方式改变您授权我们继续收集个人信息的范围或撤回您的授权。您也可以通过注销账户的方式，撤回我们继续收集您个人信息的全部授权。\n请您理解，每个业务功能需要一些基本的个人信息才能得以完成，当您撤回同意或授权后，我们无法继续为您提供撤回同意或授权所对应的服务，也不再处理您相应的个人信息。但您撤回同意或授权的决定，不会影响此前基于您的授权而开展的个人信息处理。\n\n六、变更\n我们可能会适时对本指引进行修订。当本指引的条款发生变更时，我们会在版本更新时以适当的方式向您提示变更后的隐私保护指引，并向您说明生效日期。请您仔细阅读变更后的隐私保护指引内容，您继续使用本服务表示您同意我们按照更新后的隐私保护指引处理您的个人信息。\n\n七、未成年人保护\n我们非常重视对未成年人个人信息的保护。\n根据相关法律法规的规定，若您是18周岁以下的未成年人，在使用本服务前，应事先取得您的家长或法定监护人的同意。若您是未成年人的监护人，当您对您所监护的未成年人的个人信息有相关疑问时，请通过第八条“联系我们”与我们联系。\n\n八、联系我们\n如您对本指引或其他相关事宜有疑问的，请将您的问题发送至客服，我们将尽快审核所涉问题，并在验证您的用户身份后的十五天内予以回复。（正文完）\n\n【请在此处输入小程序名称】\n',
     textAlign: 'left',
     textColor: 'rgb(0, 0, 0)',
     userSelect: true,
     _parentId: 'id246',
     _order: 0,
     widgetType: 'gsd-h5-react:Text' } }
/** widget event listeners **/
const evtListeners = {
  onid204$tap: [
    {
      key: 'wa68h3h9nrg8',
      handler:  handlers.openLocation ,
      data: { target: '' },
      boundData: {}
    },
  ],
  onid188$submit: [
    {
      key: 'wak08k90tnsg',
      handler:  handlers.submit ,
      data: { target: '$page.dataset.state.formInfo' },
      boundData: {}
    },
  ],
  onid189$change: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.value = event.detail.value } ,
      data: {},
      boundData: {}
    },
  ],
  onid189$blur: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = false } ,
      data: {},
      boundData: {}
    },
  ],
  onid189$focus: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = true } ,
      data: {},
      boundData: {}
    },
  ],
  onid190$change: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.value = event.detail.value } ,
      data: {},
      boundData: {}
    },
  ],
  onid190$blur: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = false } ,
      data: {},
      boundData: {}
    },{
      key: 'walactna4q3',
      handler:  handlers.validate ,
      data: { target: 'phone' },
      boundData: {}
    },
  ],
  onid190$focus: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = true } ,
      data: {},
      boundData: {}
    },
  ],
  onid191$change: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.value = event.detail.value } ,
      data: {},
      boundData: {}
    },
  ],
  onid191$blur: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = false } ,
      data: {},
      boundData: {}
    },
  ],
  onid191$focus: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = true } ,
      data: {},
      boundData: {}
    },
  ],
  onid192$change: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.value = event.detail.value } ,
      data: {},
      boundData: {}
    },
  ],
  onid192$blur: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = false } ,
      data: {},
      boundData: {}
    },
  ],
  onid192$focus: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = true } ,
      data: {},
      boundData: {}
    },
  ],
  onid193$change: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.value = event.detail.value } ,
      data: {},
      boundData: {}
    },
  ],
  onid193$blur: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = false } ,
      data: {},
      boundData: {}
    },
  ],
  onid193$focus: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.focus = true } ,
      data: {},
      boundData: {}
    },
  ],
  onid226$tap: [
    {
      key: 'wa8jfiscm4f',
      handler:  handlers.openLocation ,
      data: { target: '' },
      boundData: {}
    },
  ],
  onid194$change: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.value = event.detail.value } ,
      data: {},
      boundData: {}
    },
  ],
  onid230$change: [
    {
      key: '',
      handler:  function({event, lists, forItems}, $page){const $for = forItems; return event.currentTarget.value = event.detail.value } ,
      data: {},
      boundData: {}
    },
  ],
  onid233$tap: [
    {
      key: 'wae9da6t831o',
      handler:  handlers.readAgreement ,
      data: { target: 'two' },
      boundData: {}
    },
  ],
  onid234$tap: [
    {
      key: 'wancam53vc6o',
      handler:  handlers.readAgreement ,
      data: { target: 'one' },
      boundData: {}
    },
  ],
  onid239$close: [
    {
      key: 'wadqik8l88e8',
      handler:  handlers.readAgreement ,
      data: { target: '' },
      boundData: {}
    },
  ],
}
const dataBinds = {
  id189: { 
    value: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.formInfo.name
    ); },
  },
  id190: { 
    value: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.formInfo.phone
    ); },
  },
  id191: { 
    value: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.formInfo.joinnumber
    ); },
  },
  id192: { 
    value: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.showDate.unitname
    ); },
  },
  id193: { 
    value: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.formInfo.wxnumber
    ); },
  },
  id239: { 
    visible: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.agreement
    ); },
  },
  id240: { 
    _waIf: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.distinguishAgreement==='one'
    ); },
  },
  id241: { 
    _waIf: function ($page, lists, forItems, event) {const $for = forItems; return (
      $page.dataset.state.distinguishAgreement==='two'
    ); },
  },
}

createPage('indexModel', 'indexModel', widgetProps, {}, lifecyle, state, computed, evtListeners, dataBinds, app, handlers, $page)
